#!/bin/bash

set -o errexit -o nounset -o pipefail

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

servers=({0..2}.grapheneos.network)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    rsync -rptcv --fsync --chmod=D755,F644 --delete nginx.conf $remote:/etc/nginx/nginx.conf
    rsync -rptcv --fsync --chmod=D755,F644 --delete mime.types $remote:/etc/nginx/mime.types
    ssh $remote nginx -s reload

    echo
done
