#!/bin/bash

set -o errexit -o nounset -o pipefail

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo deploy_static already locked >&2
    exit 1
fi

servers=({0..2}.grapheneos.network)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server

    rsync -rptcv --chmod=D755,F644 --delete nginx.conf $remote:/etc/nginx/nginx.conf
    ssh $remote "sync /etc/nginx/nginx.conf && nginx -s reload"

    echo
done
