#!/bin/bash

set -o errexit -o nounset -o pipefail

sha256() {
    echo -n "$(basename $1): "
    curl -s "$1" | sha256sum | cut -d ' ' -f 1
}

echo gllto.glpals.com
sha256 https://gllto.glpals.com/7day/v5/latest/lto2.dat
sha256 https://gllto.glpals.com/rtistatus4.dat
sha256 https://gllto.glpals.com/rto/v1/latest/rto.dat

echo

echo agnss.goog
sha256 https://agnss.goog/lto2.dat
sha256 https://agnss.goog/rtistatus.dat
sha256 https://agnss.goog/rto.dat

echo

echo broadcom.psds.grapheneos.org
sha256 https://broadcom.psds.grapheneos.org/lto2.dat
sha256 https://broadcom.psds.grapheneos.org/rtistatus.dat
sha256 https://broadcom.psds.grapheneos.org/rto.dat
